server:
  jsp-servlet:
    init-parameters:
      development: true
  context-path: /baby
  port: 1998
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://localhost:3306/test
    name: baby
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity
